
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController, type: :request do
  include_context 'logged_in_user'

    
 describe "GET index" do
    it "gets a 200 response" do
      get "/api/projects"
      expect(response.status).to eq(200)
    end
  end

  describe "GET show" do
    it "gets a 200 response" do
      @project = FactoryGirl.create(:project)
      @membership = FactoryGirl.create(:membership, {owner_at: Time.now})
      @project.memberships << @membership
      get "/api/projects/#{@project.id}"
      expect(response.status).to eq(200)
    end
  end

  describe "POST create" do
    
    it "gets a 422 response with no params" do
      post "/api/projects/", {}, @auth_headers
      expect(response.status).to eq(422)
    end

    it "gets a 201 response with correct params" do
      @project = FactoryGirl.build(:project)
      post "/api/projects/", {name: @project.name, description: @project.description}, @auth_headers
      expect(response.status).to eq(201)
    end
  end

  describe "PUT update" do
    
    it "gets a 422 response invalid params" do
      @project = FactoryGirl.create(:project)
      put "/api/projects/#{@project.id}", {name: nil, description: nil}, @auth_headers
      expect(response.status).to eq(422)
    end

    it "gets a 201 response with correct params" do
      @project = FactoryGirl.create(:project)
      put "/api/projects/#{@project.id}", {name: @project.name, description: @project.description}, @auth_headers
      expect(response.status).to eq(204)
    end
  end

  describe "Destroy user" do
    
    it "gets a 201 response with correct params" do
      @project = FactoryGirl.create(:project)
      delete "/api/projects/#{@project.id}", {}, @auth_headers
      @test = Project.find_or_create_by(id: @project.id)
      expect(@test.persisted?).to eq(false)
    end
  end


end

