default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: project_desperado_dev

test:
  <<: *default
  database: project_desperado_test

production:
  <<: *default
  database: project_desperado_prod